name: Build the .zip file for auto-updatet using latest Thingino FW

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Build stuff
      run: make

    - uses: actions/upload-artifact@v4
      with:
        name: GeneratedZipFilesForPersonalCameras
        path: personal*.zip

